function shell({ title, eyebrow, body, action, foot = '' }) {
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="light"><meta name="robots" content="noindex,nofollow">
<title>${title} · DSH Pocket</title><style>
:root{--navy:#0b1f33;--ink:#132735;--muted:#657985;--paper:#f4f7f9;--line:#d7e1e6;--mint:#21b889;--mint-dark:#08775a;--danger:#b93648}*{box-sizing:border-box}body{margin:0;min-height:100svh;background:linear-gradient(145deg,#e7eff3 0,#f7fafb 48%,#edf4f1 100%);color:var(--ink);font-family:"Segoe UI Variable","PingFang SC","Microsoft YaHei",system-ui,sans-serif;display:grid;place-items:center;padding:24px}main{width:min(440px,100%);background:rgba(255,255,255,.94);border:1px solid rgba(11,31,51,.14);box-shadow:0 24px 70px rgba(11,31,51,.12);display:grid;grid-template-columns:9px 1fr;overflow:hidden}.rail{background:var(--navy);position:relative}.rail:after{content:"";position:absolute;width:9px;height:72px;top:40px;left:0;background:var(--mint)}.content{padding:34px 30px 28px}.eyebrow{font:700 11px/1.2 ui-monospace,SFMono-Regular,Consolas,monospace;letter-spacing:.14em;text-transform:uppercase;color:var(--mint-dark);margin-bottom:18px}h1{font-size:26px;line-height:1.18;letter-spacing:-.025em;margin:0 0 12px;color:var(--navy)}p{font-size:14px;line-height:1.7;margin:0;color:var(--muted)}.action{margin-top:26px}.stack{display:grid;gap:12px}label{font-size:12px;font-weight:650;color:var(--ink)}input{width:100%;border:1px solid var(--line);background:#fff;padding:13px 14px;font:inherit;color:var(--ink);outline:none}input:focus{border-color:var(--mint-dark);box-shadow:0 0 0 3px rgba(33,184,137,.14)}button,.button-link{width:100%;border:0;background:var(--navy);color:#fff;padding:13px 16px;font:700 14px/1.2 inherit;cursor:pointer}.button-link{display:block;text-align:center;text-decoration:none;margin-top:18px}button:disabled{opacity:.58;cursor:wait}.error{margin-top:14px;color:var(--danger);font-size:13px;line-height:1.5;border-left:3px solid var(--danger);padding-left:10px}.complete{border-top:1px solid var(--line);padding-top:18px}.complete strong{display:block;color:var(--navy);margin-bottom:6px}.foot{margin-top:24px;padding-top:16px;border-top:1px solid var(--line);font-size:11px;line-height:1.6;color:#7c8c95}@media(max-width:480px){body{padding:0;place-items:stretch}main{width:100%;min-height:100svh;border:0;box-shadow:none}.content{padding:calc(28px + env(safe-area-inset-top)) 24px calc(24px + env(safe-area-inset-bottom))}}</style></head><body><main><div class="rail" aria-hidden="true"></div><section class="content"><div class="eyebrow">${eyebrow}</div>${body}<div class="action">${action}</div><div id="error" class="error" hidden role="alert"></div>${foot ? `<div class="foot">${foot}</div>` : ''}</section></main><script src="/pocket-auth/auth-v2.js" defer></script></body></html>`;
}
export function deviceLoginPage({ deviceCount = 0, paired = false } = {}) {
  if (!deviceCount) return shell({ title: '等待设备配对', eyebrow: 'Approved device only', body: '<h1>这台电脑尚未批准设备</h1><p>请回到电脑本机，在 DSH Pocket 设置中添加并批准一台设备。</p>', action: '<button type="button" disabled>等待电脑批准设备</button>' });
  if (!paired) return shell({ title: '浏览器尚未配对', eyebrow: 'Device credential required', body: '<h1>此浏览器尚未配对</h1><p>仅知道设备密码不能登录。请回到电脑本机生成二维码，用当前浏览器重新完成配对。</p>', action: '<button type="button" disabled>需要重新配对</button>', foot: '更换浏览器或清除浏览数据后，都需要重新配对。' });
  return shell({ title: '输入设备密码', eyebrow: 'Approved device', body: '<h1>输入设备密码</h1><p>这是配对当前浏览器时设置的独立密码。DSH Pocket 不会显示或找回密码。</p>', action: '<form id="login-form" class="stack" autocomplete="off"><label for="login-password">设备密码</label><input id="login-password" type="password" minlength="6" maxlength="256" autocomplete="off" autocapitalize="none" spellcheck="false" required><button id="login-button" type="submit">进入 DSH</button></form>', foot: '连续 10 分钟没有点击、触摸或键盘操作后，需要重新输入设备密码。' });
}
export function devicePairPage() {
  return shell({ title: '绑定设备', eyebrow: 'One-time pairing', body: '<h1>申请绑定当前浏览器</h1><p>填写后还需要回到电脑本机点击“允许”。二维码和密码都不能单独授予访问权限。</p>', action: '<form id="pair-form" class="stack" autocomplete="off"><label for="device-name">设备名称</label><input id="device-name" maxlength="80" autocomplete="off" placeholder="例如：荣耀 50 Chrome" required><label for="device-password">设备密码</label><input id="device-password" type="password" minlength="6" maxlength="256" autocomplete="off" autocapitalize="none" spellcheck="false" placeholder="至少 6 个字符" required><label for="device-password-confirm">再次输入设备密码</label><input id="device-password-confirm" type="password" minlength="6" maxlength="256" autocomplete="off" autocapitalize="none" spellcheck="false" required><button id="pair-button" type="submit">提交配对申请</button></form><div id="pair-complete" class="complete" hidden><strong>配对申请已提交</strong><p>现在可以关闭页面。电脑批准后，重新打开固定网址并输入设备密码。</p><a class="button-link" href="/">电脑已批准，进入 DSH</a></div>', foot: '配对链接和申请 5 分钟后失效；过期后请回电脑重新生成。' });
}

/** 仅真实用户交互续期；自动网络流量、WS 心跳和前台静置都不会续期。 */
export const SESSION_ACTIVITY_SCRIPT = `<script data-dsh-pocket-session-activity="1">!function(){try{var last=0,busy=false;function send(){var now=Date.now();if(busy||now-last<15000)return;last=now;busy=true;fetch('/pocket-auth/activity',{method:'POST',credentials:'same-origin',cache:'no-store'}).then(function(r){if(r.status===401)location.replace('/')}).catch(function(){}).finally(function(){busy=false})}['pointerdown','keydown','touchstart'].forEach(function(n){document.addEventListener(n,send,{passive:true,capture:true})})}catch(e){}}();</script>`;
